//FOLLOWERS
export const USER_START = "USER_START";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const USER_FINISH = "USER_FINISH";

//FOLLOWERS
export const FOLLOWERS_LIST_START = "FOLLOWERS_LIST_START";
export const FOLLOWERS_LIST_SUCCESS = "FOLLOWERS_LIST_SUCCESS";
export const FOLLOWERS_LIST_ERROR = "FOLLOWERS_LIST_ERROR";
export const FOLLOWERS_LIST_FINISH = "FOLLOWERS_LIST_FINISH";

//PAGINATION
// export const CHANGE_USERNAME = "CHANGE_USERNAME";
// export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
// export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const TABLE_CHANGE_PAGE = "TABLE_CHANGE_PAGE";
